# Generated by Django 3.2 on 2021-04-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.CharField(default='JohnSmith@abc.edu', max_length=1000)),
                ('site_URL', models.CharField(default='https://www.google.com/', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Parameters',
                'verbose_name_plural': 'Site Parameters',
            },
        ),
    ]
