# Generated by Django 3.2 on 2021-04-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_subject', models.CharField(default='Message Subject', max_length=300, verbose_name='Message Subject')),
                ('message_text', models.CharField(default='Message Text', max_length=10000, verbose_name='Message Text')),
                ('user_list', models.JSONField(verbose_name='User List')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mass Email',
                'verbose_name_plural': 'Mass Emails',
            },
        ),
    ]
