# Generated by Django 4.0.3 on 2022-04-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitBitUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitbit_user_id', models.CharField(default='', max_length=100, verbose_name='FitBit User ID')),
                ('fitbit_access_token', models.CharField(default='', max_length=1000, verbose_name='FitBit Access Token')),
                ('fitbit_refresh_token', models.CharField(default='', max_length=1000, verbose_name='FitBit Refresh Token')),
                ('fitbit_last_synced', models.DateTimeField(default=None, null=True, verbose_name='FitBit Last Synced')),
                ('fitbit_time_zone', models.CharField(default='', max_length=1000, verbose_name='FitBit Time Zone')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fitbit User',
                'verbose_name_plural': 'Fitbit Users',
            },
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_url', models.CharField(default='', max_length=1000, verbose_name='Return URL')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registration Request',
                'verbose_name_plural': 'Registration Requests',
            },
        ),
    ]
