# Generated by Django 4.0.3 on 2022-04-04 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fitbituser_registrationrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitbituser',
            old_name='fitbit_access_token',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='fitbituser',
            old_name='fitbit_last_synced',
            new_name='last_synced',
        ),
        migrations.RenameField(
            model_name='fitbituser',
            old_name='fitbit_refresh_token',
            new_name='refresh_token',
        ),
        migrations.RenameField(
            model_name='fitbituser',
            old_name='fitbit_time_zone',
            new_name='time_zone',
        ),
        migrations.RenameField(
            model_name='fitbituser',
            old_name='fitbit_user_id',
            new_name='user_id',
        ),
    ]
