# Generated by Django 4.0.3 on 2022-04-19 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_fitbit_access_token_fitbituser_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitbituser',
            name='last_synced',
        ),
        migrations.RemoveField(
            model_name='fitbituser',
            name='time_zone',
        ),
    ]
