# Generated by Django 3.2 on 2021-04-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_massemail_email_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massemail',
            name='email_count',
        ),
        migrations.AddField(
            model_name='massemail',
            name='email_result',
            field=models.JSONField(default={}, verbose_name='Email Result'),
            preserve_default=False,
        ),
    ]
