# Generated by Django 5.2.16 on 2026-08-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_fitbituser_last_synced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbituser',
            name='refresh_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FitBit Access Token Expiration Date'),
        ),
    ]
