# Generated by Django 3.2 on 2021-04-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_massemail_email_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='massemail',
            name='memo',
            field=models.CharField(default='', max_length=300, verbose_name='Memo'),
        ),
    ]
