# Generated by Django 3.2 on 2021-11-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_massemail_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massemail',
            name='message_text',
            field=models.CharField(default='Message Text', max_length=100000, verbose_name='Message Text'),
        ),
    ]
